### ISSUE TITLE
Q - There is no way to cleanup AWS resources without env being connected

### ISSUE THREAD

**Issue by Elmo33** [Altinity/terraform-provider-altinitycloud#74]
If the user started setting up environment and for some reason environment failed to connect to altinity, the user has no way to discard the config and start anew. They have to debug the initial setup and make it work and only after that can they remove the resources.

Issue is that if for some reason user changes their mind in the middle of the process, then they have to manually remove all the resources that were provisioned in the cloud.

**Comment by ianaya89** [comment]
- This how Anywhere BYOC AWS works, is not a problem of the provider itself. The only way we can access customer's AWS account is with the connect EC2 instance. Without it, we as admin can't also remove the resources and will always require manual procedures.
- If the connection never worked, there is no issue because nothing was created. 
- If the connection worked but is not working anymore, it will require EC2 instance debugging. We can add a section in the docs to show how to do that (if it's missing). This EC2 instance could be created with or without Terraform, the docs should be at a global level (not only in Terraform setup)
- The config can be discarded at any time, they just need to be responsible for the created resources
- Users can still destroy the environment using `skip_deprovision_on_destroy=true`
- This is not entirely correct. If the connection is stablished they can do and redo whatever they want. 👇
```
Issue is that if for some reason user changes their mind in the middle of the process, then they have to manually remove all the resources that were provisioned in the cloud.
```

**Comment by Elmo33** [comment]
closing since related bugs were fixed so far.
